### ISSUE TITLE
Can I declare the useUpload and use it later in some event like the useMutation one ?

### ISSUE THREAD

**Issue by justicejoe** [zackify/react-use-upload#6]
now it just start uploading when i finish selecting the file.
But what I want is to select the file first then click button to start upload.

**Comment by justicejoe** [comment]
@zackify

**Comment by zackify** [comment]
You would need to maintain two states. 

let [selectedFiles, setSelectedFiles ] = useState()

let [filesReadyForUpload, setFilesReadyForUpload] = useState()

<input onChange={files => setSelectedFiles(files)} />

Now, whenever you want to actually trigger the upload. Like pressing a button, you would setFilesReadyForUpload(selectedFiles)

The library doesn’t care about when “files” is set in the options. That’s up to you to control :)

**Comment by justicejoe** [comment]
@zackify Ok Thank you so much for your answer :D 
One more question, is there a way to detect the network timeout , or internet connection in case of failed upload using this module ?

**Comment by zackify** [comment]
You can test that yourself and make sure. It’s been a while since I used this. But I need to use it for an upcoming project soon....

Anyways, the library returns “error” to you. That should contain any xhr error such as a timeout or network failure. If there’s a bug let me know, I will fix it. 

I was just learning react hooks when I migrated this over, and TS. It could use some cleanup anyway!
